[package]
name = "outdatui"
version = "0.1.0"
edition = "2024"
description = "lorem ipsum"
license = "MIT"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"

# Read the optimization guideline for more details: https://ratatui.rs/recipes/apps/release-your-app/#optimizations
[profile.release]
opt-level = "s"
strip = true
lto = true
codegen-units = 1
