[package]
name = "outdatui"
version = "0.1.0"
edition = "2024"
description = "lorem ipsum"
license = "MIT"

[dependencies]
ratatui = "0.29.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

# Read the optimization guideline for more details: https://ratatui.rs/recipes/apps/release-your-app/#optimizations
[profile.release]
opt-level = "s"
strip = true
lto = true
codegen-units = 1
